### ISSUE TITLE
Manual does not load

### ISSUE THREAD

**Issue by Benman2785** [JohnImril/diablo_web_simple#11]
Hi,

your new feature D1_manual_en.pdf does not work -> it goes to webroot and there is no D1_manual_en.pdf -> if i change the href to ../diablo_web_simple/D1_manual_en.pdf it simply opens a new tab with the same screen

**Comment by JohnImril** [comment]
oh, it opens locally, the problem may be with relative paths, removed / before the file. Does this work?

**Comment by Benman2785** [comment]
we dont have 404 anymore -> but it still doesnt load as it reloads the screen -> even if the URL is now https://hoffmeister.li/diablo_web_simple/D1_manual_en.pdf

if i delete cache it works fine until i load https://hoffmeister.li/diablo_web_simple/diablo_web_simple
i had the same error when i put my "loader.html" into /diablo_web(_simple) -> it only worked once and then it always showed the normal diablo_web_simple loading screen

here a video: https://youtu.be/P6UzSWGN_V8

**Comment by JohnImril** [comment]
unfortunately it is not possible to check this locally, but I have uploaded another way to solve this problem, please check it

**Comment by Benman2785** [comment]
its trying to read from "https://hoffmeister.li/diablo_web_simple/assets/assets/" now -> so one /assets to much = not working yet

**Comment by JohnImril** [comment]
and does the file itself get into the build on the server, if so, where is it located?

**Comment by JohnImril** [comment]
files are not located through the browser or you do not see them directly on the server after the build? Can you take a screenshot of what is in this folder on the server after the build?

**Comment by Benman2785** [comment]
![assets_manual](https://github.com/user-attachments/assets/99340d92-4d7a-4f09-8326-c751e3b72ae0)
![assets_manual_2](https://github.com/user-attachments/assets/e2d050ab-0292-4d39-ad22-e6f451e18008)

**Comment by JohnImril** [comment]
thanks, I'm looking into what could have gone wrong.

**Comment by JohnImril** [comment]
I changed paths throughout the app. Does this work?

**Comment by Benman2785** [comment]
i dont have the errors now -> but it still doesnt load the pdf
as described: i have this behaviour too if it use my loader.html in the same folder as diablo_web_simple = it only works once and then it loads the normal diablo_web_simple page from javascript. 
same behaviour in Chrome and Firefox

**Comment by JohnImril** [comment]
added another fix, does it work?

**Comment by Benman2785** [comment]
THANK YOU -> it works fine now :)

btw for my use i also added the german manual and my "stretched Fullscreen" text like this:

j.jsx("div",{className:"start-screen__description",children:"Press F8 to toggle between 4:3 and stretched"}),j.jsx("a",{className:"start-screen__manual-link",href:"/diablo_web_simple/manual_en.pdf",target:"_blank",rel:"noopener noreferrer",children:"View Manual"}),j.jsx("div",{}),j.jsx("a",{className:"start-screen__manual-link",href:"/diablo_web_simple/manual_de.pdf",target:"_blank",rel:"noopener noreferrer",children:"zeige Handbuch"})

**Comment by Benman2785** [comment]
j.jsx("div",{className:"start-screen__description",children:"Press F8 to toggle between 4:3 and stretched"}),
j.jsx("a",{className:"start-screen__manual-link",href:"/diablo_web_simple/manual_en.pdf",target:"_blank",rel:"noopener noreferrer",children:"View Manual"}),
j.jsx("div",{}),
j.jsx("a",{className:"start-screen__manual-link",href:"/diablo_web_simple/manual_de.pdf",target:"_blank",rel:"noopener noreferrer",children:"zeige Handbuch"})
