### ISSUE TITLE
Request: add my stretched Fullscreen

### ISSUE THREAD

**Issue by Benman2785** [JohnImril/diablo_web_simple#16]
Hi,

please add my code natively to index-*.js
also maybe you get the text on shown website to look nicer than my workaround

CODE:
// Toggle for Aspect Ratio (4:3 / 16:9)
let isWide = false; // Default to 4:3

// Function to toggle aspect ratio
function toggleAspectRatio() {
const appBodyInner = document.querySelector('.app__inner');
const appBodyOuter = document.querySelector('.app__body');

if (isWide) {
// Set to 4:3 aspect ratio
appBodyInner.style.width = 'calc(400vh / 3)';
appBodyInner.style.maxHeight = 'calc(75vw * 0.75)';
appBodyOuter.style.left = 'calc(50% - 200vh / 3)';
} else {
// Set to 16:9 aspect ratio (Fullscreen)
appBodyInner.style.width = '100vw';
appBodyInner.style.height = '100vh';
appBodyOuter.style.left = '0';
}

// Toggle the state
isWide = !isWide;
}

// Listen for key press to toggle aspect ratio
document.addEventListener('keydown', function(event) {
if (event.key === 'F8') { // Use 'F8' to toggle the aspect ratio
toggleAspectRatio();
}
});

**Comment by Benman2785** [comment]
https://www.youtube.com/watch?v=ByfRze_6mio

**Comment by JohnImril** [comment]
hi, and it doesn't work on F9 now?

**Comment by Benman2785** [comment]
hi,
i use F8 now, as this key is in the onscreen keyboard (yet the diablo_web_simple onscreen keyboard is not working)
when using F8 on Desktop it stretches the game to any aspect-ratio on any screen :)

**Comment by Benman2785** [comment]
ahhh - i totally missed the point where you added the function already on F9 :)
THANK YOU
