### ISSUE TITLE
include manual into the start screen

### ISSUE THREAD

**Issue by Benman2785** [JohnImril/diablo_web_simple#4]
hi,

would be great if we can use google pdfviewer to show Diablos manual (https://hoffmeister.li/downloads/games/diablo_1/D1_manual_en.pdf)
if we add an 69px header with the "back to menu" button it should look fine

code looks like this:
<object style="width:100%;height:calc(100% - 69px)" data="../D1_manual.pdf" type="application/pdf">
    <iframe style="width:100%;height:calc(100% - 69px)" src="https://docs.google.com/viewer?url=https://YOUR.URL/diablo_web_simple/D1_manual.pdf&embedded=true"></iframe>

also: i can try to make an png with all hotkeys (like toggle 4:3/stretched) -> this could also be a menu point

**Comment by JohnImril** [comment]
I added a manual, but it weighs about 3 MB, so if the user has a very slow Internet, it may slightly affect the page loading speed
